default_language_version:
  python: python

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: debug-statements
        exclude: debuggers.py


  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0 
    hooks:
      - id: flake8
        exclude: "^tilt"
        args: ["-j8", "--ignore=E501"]
        additional_dependencies:
          - importlib_metadata>=4.10.0

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
      - id: pyupgrade
        exclude: "^tilt"
        args: [--py38-plus]

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.13.0
    hooks:
      - id: reorder-python-imports
        args: [--py38-plus]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy
        exclude: "^tilt"
        additional_dependencies:
          - --no-compile
          - types-requests==2.28.1

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-use-type-annotations
