# Generated by Django 5.0.6 on 2024-09-30 03:39
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corepath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tronco Común')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('status_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Core',
                'db_table': 'Core',
            },
        ),
        migrations.CreateModel(
            name='SubCorePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Sub Tronco')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('status_delete', models.BooleanField(default=False)),
                ('core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathcore.corepath')),
            ],
            options={
                'verbose_name': 'SubPaths',
                'db_table': 'SubCorePath',
            },
        ),
        migrations.CreateModel(
            name='CoreUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('url_repo', models.URLField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_delete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sub_core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathcore.subcorepath')),
            ],
            options={
                'verbose_name': 'CoreUser',
                'db_table': 'CoreUser',
            },
        ),
    ]
